CREATE DATABASE BANCO 1CREATE TABLE CUENTA CORRIENTE (
	ID CLIENTE SERIAL NOT NULL,
	NOMBRE CLIENTE VARCHAR ( 30 ) NOT NULL,
	MONTO NUMERIC NOT NULL,
	CONSTRAINT PK CUENTA CORRIENTE PRIMARY KEY ( ID CLIENTE ) 
);
CREATE TABLE CUENTA AHORROS (
	ID CLIENTE SERIAL NOT NULL,
	NOMBRE CLIENTE VARCHAR ( 30 ) NOT NULL,
	MONTO NUMERIC NOT NULL,
	CONSTRAINT PK CUENTA AHORROS PRIMARY KEY ( ID CLIENTE ) 
);
CREATE TABLE BITACORA (
	ID BITACORA SERIAL NOT NULL,
	TIEMPO TIME WITH TIME ZONE,
	DESCRIPCION VARCHAR ( 150 ),
CONSTRAINT PK LOG PRIMARY KEY ( ID BITACORA ) 
);